import car1 from './img/car1.jpg'
import car2 from './img/car2.jpg'
import car3 from './img/car3.jpg'
import car4a from './img/car4-1.jpg'
import car4b from './img/car4-2.jpg'
import car5a from './img/car5-1.jpg'
import car5b from './img/car5-2.jpg'
import car6a from './img/car6-1.jpg'
import car6b from './img/car6-2.jpg'
import car7a from './img/car7-1.jpg'
import car7b from './img/car7-2.jpg'
import car8a from './img/car8-1.jpg'
import car8b from './img/car8-2.jpg'
import car9a from './img/car9-1.jpg'
import car9b from './img/car9-2.jpg'
import car10a from './img/car10-1.jpg'
import car10b from './img/car10-2.jpg'
import car11a from './img/car11-1.jpg'
import car11b from './img/car11-2.png'
import car12a from './img/car12-1.png'
import car12b from './img/car12-2.jpg'

export const card_data=[
    {
        carname:'Toyata',
        imageSource1:car1,
        imageSource2:car1,
        capacity: " 5",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2021'
    },
    {
        carname:'BMW',
        imageSource1:car2,
        imageSource2:car2,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car3,
        imageSource2:car3,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car4a,
        imageSource2:car4b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Bugati',
        imageSource1:car5a,
        imageSource2:car5b, 
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car6a,
        imageSource2:car6b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car7a,
        imageSource2:car7b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car8a,
        imageSource2:car8b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car9a,
        imageSource2:car9b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car10a,
        imageSource2:car10b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car11a,
        imageSource2:car11b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car12a,
        imageSource2:car12b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Toyata',
        imageSource1:car1,
        imageSource2:car1,
        capacity: " 5",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2021'
    },
    {
        carname:'BMW',
        imageSource1:car2,
        imageSource2:car2,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car3,
        imageSource2:car3,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car4a,
        imageSource2:car4b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Bugati',
        imageSource1:car5a,
        imageSource2:car5b, 
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car6a,
        imageSource2:car6b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car7a,
        imageSource2:car7b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car8a,
        imageSource2:car8b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car9a,
        imageSource2:car9b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car10a,
        imageSource2:car10b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car11a,
        imageSource2:car11b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car12a,
        imageSource2:car12b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Toyata',
        imageSource1:car1,
        imageSource2:car1,
        capacity: " 5",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2021'
    },
    {
        carname:'BMW',
        imageSource1:car2,
        imageSource2:car2,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car3,
        imageSource2:car3,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car4a,
        imageSource2:car4b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Bugati',
        imageSource1:car5a,
        imageSource2:car5b, 
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car6a,
        imageSource2:car6b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car7a,
        imageSource2:car7b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car8a,
        imageSource2:car8b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car9a,
        imageSource2:car9b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car10a,
        imageSource2:car10b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car11a,
        imageSource2:car11b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car12a,
        imageSource2:car12b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Toyata',
        imageSource1:car1,
        imageSource2:car1,
        capacity: " 5",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2021'
    },
    {
        carname:'BMW',
        imageSource1:car2,
        imageSource2:car2,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car3,
        imageSource2:car3,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car4a,
        imageSource2:car4b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Bugati',
        imageSource1:car5a,
        imageSource2:car5b, 
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car6a,
        imageSource2:car6b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car7a,
        imageSource2:car7b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car8a,
        imageSource2:car8b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car9a,
        imageSource2:car9b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car10a,
        imageSource2:car10b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car11a,
        imageSource2:car11b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car12a,
        imageSource2:car12b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Toyata',
        imageSource1:car1,
        imageSource2:car1,
        capacity: " 5",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2021'
    },
    {
        carname:'BMW',
        imageSource1:car2,
        imageSource2:car2,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car3,
        imageSource2:car3,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Mustang',
        imageSource1:car4a,
        imageSource2:car4b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Bugati',
        imageSource1:car5a,
        imageSource2:car5b, 
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car6a,
        imageSource2:car6b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car7a,
        imageSource2:car7b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car8a,
        imageSource2:car8b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car9a,
        imageSource2:car9b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car10a,
        imageSource2:car10b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car11a,
        imageSource2:car11b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },{
        carname:'Ford',
        imageSource1:car12a,
        imageSource2:car12b,
        capacity:"4",
        milage:'7km/liter',
        fuel:'Petrol',
        driver:'Automatic',
        EMI:'$420/month',
        year:'2022'
    },
]